export enum HttpStatusMessages {
  IS_NOT_CEMIG_INVOICE = 'Erro ao tentar processar sua fatura, verifique se o documento que você enviou é uma fatura CEMIG',
  ERROR_PROCESSING_INVOICES = 'Erro ao processar faturas:',
  ERROR_GETIING_ALL_INVOICES = 'Erro ao obter todas as faturas:',
  ERROR_CREATING_INVOICES = 'Erro ao criar faturas no banco de dados:',
  INVOICE_ALREADY_EXISTS = 'Erro ao criar fatura no banco de dados: Fatura já existente encontrada ID',
  INVOICES_ALREADY_EXISTS = 'Erro ao criar as faturas no banco de dados: Todas as faturas já são existentes',
  PDF_PROCESSING_SUCCESSFULLY = 'PDF processado com sucesso',
  PDF_EXTRACT_DATA_ERROR = 'Erro ao extrair dados do PDF',
  ERROR_CALLING_NEW_INVOICE = 'Ocorreu um erro ao chamar a rota /new-invoice:',
  ERROR_GETTING_INVOICE = 'Ocorreu um erro ao tentar obter uma fatura:',
  CLIENT_NUMBER_NOT_FOUND = 'Não foram encontradas faturas com esse número de cliente',
  GET_CLIENTS_ERROR = 'Ocorreu um erro ao tentar obter todos os clientes',
  GET_CLIENT_INVOICE_ERROR = 'Ocorreu um erro ao tentar obter as faturas do cliente',
  GET_CLIENT_ERROR = 'Ocorreu um erro ao tentar obter o cliente',
  CREATE_CLIENT_ALREADY_EXIST = 'O cliente já existe no banco de dados',
  CREATE_CLIENT_ERROR = 'Ocorreu um erro ao criar o cliente',
  UPDATE_CLIENT_ERROR = 'Ocorreu um erro ao adicionar a fatura ao cliente',
  GET_CLIENT_NOT_FOUND = 'Não foi encontrado um cliente com esse número',
}
